"""
Career Knowledge Database — Structured role data for the MCP Server.

Contains comprehensive career data for 12+ technical roles including
skills, certifications, ATS keywords, interview topics, learning resources,
and project recommendations.
"""

CAREER_ROLES: dict = {
    "software_engineer": {
        "metadata": {
            "id": "software_engineer",
            "title": "Software Engineer",
            "description": "Design, develop, test, and maintain software applications and systems.",
            "industry": "Technology",
            "experience_level": "Entry to Mid-Level",
            "avg_salary_range": "$70,000 - $150,000",
        },
        "must_have_skills": [
            "Data Structures & Algorithms",
            "Object-Oriented Programming",
            "Python",
            "Java",
            "Git & Version Control",
            "SQL & Database Management",
            "REST APIs",
            "Problem Solving",
            "Unit Testing",
            "Linux/Command Line",
        ],
        "good_to_have_skills": [
            "System Design",
            "Docker",
            "Cloud Services (AWS/GCP/Azure)",
            "CI/CD Pipelines",
            "Microservices Architecture",
            "GraphQL",
            "Redis",
            "Kubernetes",
            "TypeScript",
            "Agile/Scrum Methodology",
        ],
        "soft_skills": [
            "Communication",
            "Teamwork",
            "Problem Solving",
            "Time Management",
            "Adaptability",
            "Critical Thinking",
            "Attention to Detail",
        ],
        "ats_keywords": [
            "software development", "full lifecycle", "agile", "scrum",
            "object-oriented", "data structures", "algorithms", "REST API",
            "microservices", "cloud computing", "CI/CD", "unit testing",
            "code review", "version control", "git", "debugging",
            "performance optimization", "scalable systems", "SDLC",
            "design patterns", "test-driven development", "TDD",
        ],
        "interview_topics": [
            "Data Structures (Arrays, Trees, Graphs, Hash Maps)",
            "Algorithm Design (Sorting, Searching, Dynamic Programming)",
            "System Design Fundamentals",
            "Object-Oriented Design Principles (SOLID)",
            "Database Design & SQL Queries",
            "Concurrency & Multithreading",
            "API Design & REST Principles",
            "Behavioral Questions (STAR Method)",
            "Code Debugging & Optimization",
            "Time & Space Complexity Analysis",
        ],
        "certifications": [
            {"name": "AWS Certified Developer – Associate", "provider": "Amazon", "difficulty": "Intermediate"},
            {"name": "Google Associate Cloud Engineer", "provider": "Google", "difficulty": "Intermediate"},
            {"name": "Oracle Certified Professional Java SE", "provider": "Oracle", "difficulty": "Intermediate"},
            {"name": "Microsoft Certified: Azure Developer", "provider": "Microsoft", "difficulty": "Intermediate"},
        ],
        "project_recommendations": [
            {
                "title": "Task Management API",
                "description": "Build a RESTful API with authentication, CRUD operations, and database integration.",
                "skills_demonstrated": ["REST API", "Database", "Authentication", "Testing"],
                "difficulty": "Beginner",
                "estimated_hours": 20,
            },
            {
                "title": "Real-Time Chat Application",
                "description": "Implement a WebSocket-based chat app with user rooms and message persistence.",
                "skills_demonstrated": ["WebSockets", "Real-time Systems", "Database", "Frontend"],
                "difficulty": "Intermediate",
                "estimated_hours": 40,
            },
            {
                "title": "URL Shortener Service",
                "description": "Create a scalable URL shortener with analytics, rate limiting, and caching.",
                "skills_demonstrated": ["System Design", "Caching", "Database", "API Design"],
                "difficulty": "Intermediate",
                "estimated_hours": 30,
            },
        ],
        "learning_resources": [
            {"name": "LeetCode", "url": "https://leetcode.com", "type": "Practice", "free": True},
            {"name": "MIT OpenCourseWare - Intro to Algorithms", "url": "https://ocw.mit.edu", "type": "Course", "free": True},
            {"name": "Designing Data-Intensive Applications", "url": "https://dataintensive.net", "type": "Book", "free": False},
            {"name": "freeCodeCamp", "url": "https://freecodecamp.org", "type": "Course", "free": True},
            {"name": "The Odin Project", "url": "https://theodinproject.com", "type": "Course", "free": True},
        ],
        "difficulty": "Medium",
        "average_preparation_weeks": 12,
    },

    "frontend_developer": {
        "metadata": {
            "id": "frontend_developer",
            "title": "Frontend Developer",
            "description": "Build responsive, performant user interfaces for web applications.",
            "industry": "Technology",
            "experience_level": "Entry to Mid-Level",
            "avg_salary_range": "$60,000 - $140,000",
        },
        "must_have_skills": [
            "HTML5 & Semantic HTML",
            "CSS3 & Responsive Design",
            "JavaScript (ES6+)",
            "React.js",
            "TypeScript",
            "Git & Version Control",
            "RESTful API Integration",
            "Browser DevTools",
            "CSS Frameworks (Tailwind/Bootstrap)",
            "Webpack/Vite Build Tools",
        ],
        "good_to_have_skills": [
            "Next.js",
            "State Management (Redux/Zustand)",
            "Testing (Jest, Cypress)",
            "GraphQL",
            "Web Accessibility (WCAG)",
            "Performance Optimization",
            "PWA Development",
            "Figma/Design Tools",
            "Animation Libraries (Framer Motion)",
            "SEO Best Practices",
        ],
        "soft_skills": [
            "Eye for Design",
            "Communication",
            "User Empathy",
            "Attention to Detail",
            "Collaboration",
            "Creativity",
            "Problem Solving",
        ],
        "ats_keywords": [
            "frontend development", "React", "JavaScript", "TypeScript",
            "responsive design", "CSS", "HTML", "user interface",
            "web application", "component-based", "state management",
            "API integration", "performance optimization", "accessibility",
            "cross-browser compatibility", "mobile-first", "SPA",
            "single page application", "UI/UX", "webpack", "vite",
        ],
        "interview_topics": [
            "JavaScript Fundamentals (Closures, Prototypes, Event Loop)",
            "React Concepts (Hooks, Virtual DOM, Lifecycle)",
            "CSS Layout (Flexbox, Grid, Positioning)",
            "Web Performance Optimization",
            "Browser Rendering Pipeline",
            "Accessibility Standards (ARIA, WCAG)",
            "State Management Patterns",
            "API Integration & Error Handling",
            "Frontend Security (XSS, CSRF)",
            "Build Tools & Module Bundlers",
        ],
        "certifications": [
            {"name": "Meta Front-End Developer Professional Certificate", "provider": "Meta/Coursera", "difficulty": "Beginner"},
            {"name": "AWS Certified Cloud Practitioner", "provider": "Amazon", "difficulty": "Beginner"},
            {"name": "Google UX Design Professional Certificate", "provider": "Google/Coursera", "difficulty": "Beginner"},
        ],
        "project_recommendations": [
            {
                "title": "Portfolio Website with Animations",
                "description": "Build a stunning portfolio with smooth animations, dark mode, and responsive design.",
                "skills_demonstrated": ["CSS", "JavaScript", "Responsive Design", "Animations"],
                "difficulty": "Beginner",
                "estimated_hours": 15,
            },
            {
                "title": "E-Commerce Dashboard",
                "description": "Create a React dashboard with charts, filters, search, and real-time data.",
                "skills_demonstrated": ["React", "State Management", "Charts", "API Integration"],
                "difficulty": "Intermediate",
                "estimated_hours": 35,
            },
            {
                "title": "Collaborative Whiteboard App",
                "description": "Build a real-time drawing app with canvas API and WebSocket sync.",
                "skills_demonstrated": ["Canvas API", "WebSockets", "React", "Real-time"],
                "difficulty": "Advanced",
                "estimated_hours": 50,
            },
        ],
        "learning_resources": [
            {"name": "Frontend Masters", "url": "https://frontendmasters.com", "type": "Course", "free": False},
            {"name": "JavaScript.info", "url": "https://javascript.info", "type": "Tutorial", "free": True},
            {"name": "CSS Tricks", "url": "https://css-tricks.com", "type": "Reference", "free": True},
            {"name": "React Official Docs", "url": "https://react.dev", "type": "Documentation", "free": True},
            {"name": "Scrimba", "url": "https://scrimba.com", "type": "Interactive", "free": True},
        ],
        "difficulty": "Medium",
        "average_preparation_weeks": 10,
    },

    "backend_developer": {
        "metadata": {
            "id": "backend_developer",
            "title": "Backend Developer",
            "description": "Design and implement server-side logic, databases, and APIs.",
            "industry": "Technology",
            "experience_level": "Entry to Mid-Level",
            "avg_salary_range": "$70,000 - $150,000",
        },
        "must_have_skills": [
            "Python/Java/Node.js",
            "SQL & Relational Databases",
            "REST API Design",
            "Authentication & Authorization",
            "Data Structures & Algorithms",
            "Git & Version Control",
            "Linux Server Administration",
            "Database Design & Normalization",
            "Error Handling & Logging",
            "Security Best Practices",
        ],
        "good_to_have_skills": [
            "Docker & Containerization",
            "Message Queues (RabbitMQ/Kafka)",
            "NoSQL Databases (MongoDB/Redis)",
            "GraphQL",
            "Microservices Architecture",
            "CI/CD Pipelines",
            "Cloud Services (AWS/GCP)",
            "gRPC",
            "Caching Strategies",
            "API Rate Limiting",
        ],
        "soft_skills": [
            "Analytical Thinking",
            "System Thinking",
            "Documentation Skills",
            "Team Collaboration",
            "Problem Decomposition",
            "Communication",
        ],
        "ats_keywords": [
            "backend development", "server-side", "API development", "database design",
            "microservices", "REST", "SQL", "NoSQL", "authentication",
            "authorization", "scalability", "performance", "Docker",
            "cloud services", "CI/CD", "security", "caching",
            "message queues", "distributed systems", "ORM",
        ],
        "interview_topics": [
            "Database Design & Optimization",
            "API Design Principles (REST, GraphQL)",
            "Authentication (OAuth, JWT, Sessions)",
            "System Design & Scalability",
            "Concurrency & Distributed Systems",
            "Caching Strategies (Redis, CDN)",
            "Security (SQL Injection, XSS, CSRF)",
            "Message Queues & Event-Driven Architecture",
            "Data Structures & Algorithms",
            "DevOps & Deployment Practices",
        ],
        "certifications": [
            {"name": "AWS Certified Solutions Architect", "provider": "Amazon", "difficulty": "Intermediate"},
            {"name": "Google Professional Cloud Developer", "provider": "Google", "difficulty": "Intermediate"},
            {"name": "MongoDB Associate Developer", "provider": "MongoDB", "difficulty": "Beginner"},
        ],
        "project_recommendations": [
            {
                "title": "Authentication Microservice",
                "description": "Build a complete auth service with JWT, OAuth2, rate limiting, and password hashing.",
                "skills_demonstrated": ["Authentication", "Security", "API Design", "Database"],
                "difficulty": "Intermediate",
                "estimated_hours": 25,
            },
            {
                "title": "Job Queue Processing System",
                "description": "Create a distributed task queue with priority scheduling and retry mechanisms.",
                "skills_demonstrated": ["Message Queues", "Distributed Systems", "Database", "Monitoring"],
                "difficulty": "Advanced",
                "estimated_hours": 40,
            },
            {
                "title": "REST API with Rate Limiting & Caching",
                "description": "Build a production API with Redis caching, rate limiting, pagination, and documentation.",
                "skills_demonstrated": ["API Design", "Caching", "Performance", "Documentation"],
                "difficulty": "Intermediate",
                "estimated_hours": 30,
            },
        ],
        "learning_resources": [
            {"name": "Designing Data-Intensive Applications", "url": "https://dataintensive.net", "type": "Book", "free": False},
            {"name": "SQLBolt", "url": "https://sqlbolt.com", "type": "Interactive", "free": True},
            {"name": "FastAPI Documentation", "url": "https://fastapi.tiangolo.com", "type": "Documentation", "free": True},
            {"name": "System Design Primer", "url": "https://github.com/donnemartin/system-design-primer", "type": "Reference", "free": True},
        ],
        "difficulty": "Medium",
        "average_preparation_weeks": 12,
    },

    "full_stack_developer": {
        "metadata": {
            "id": "full_stack_developer",
            "title": "Full Stack Developer",
            "description": "Build end-to-end web applications spanning frontend, backend, and databases.",
            "industry": "Technology",
            "experience_level": "Mid-Level",
            "avg_salary_range": "$80,000 - $160,000",
        },
        "must_have_skills": [
            "JavaScript/TypeScript",
            "React or Angular or Vue",
            "Node.js or Python",
            "SQL & NoSQL Databases",
            "REST API Design & Integration",
            "Git & Version Control",
            "HTML5 & CSS3",
            "Authentication & Authorization",
            "Responsive Web Design",
            "Basic DevOps (Docker, CI/CD)",
        ],
        "good_to_have_skills": [
            "Next.js / Nuxt.js",
            "GraphQL",
            "Cloud Deployment (AWS/GCP/Vercel)",
            "WebSockets & Real-time",
            "Testing (Unit, Integration, E2E)",
            "Serverless Functions",
            "State Management",
            "Performance Optimization",
            "Monorepo Tools (Nx, Turborepo)",
            "Mobile Development (React Native)",
        ],
        "soft_skills": [
            "Versatility",
            "Quick Learning",
            "Communication",
            "Project Management",
            "Collaboration",
            "Big Picture Thinking",
        ],
        "ats_keywords": [
            "full stack", "frontend", "backend", "end-to-end",
            "JavaScript", "TypeScript", "React", "Node.js",
            "database", "API", "responsive", "cloud",
            "deployment", "agile", "full lifecycle", "web application",
            "authentication", "REST", "SQL", "DevOps",
        ],
        "interview_topics": [
            "Full Stack Architecture & Design Patterns",
            "Frontend Frameworks Deep Dive",
            "Backend API Design & Database Modeling",
            "Authentication Flows (OAuth, JWT)",
            "Performance Optimization (Frontend & Backend)",
            "DevOps & CI/CD Pipelines",
            "Data Structures & Algorithms",
            "System Design",
            "Security Best Practices",
            "Real-time Communication (WebSockets)",
        ],
        "certifications": [
            {"name": "Meta Full-Stack Engineer Certificate", "provider": "Meta/Coursera", "difficulty": "Intermediate"},
            {"name": "AWS Certified Developer – Associate", "provider": "Amazon", "difficulty": "Intermediate"},
            {"name": "Google Professional Cloud Developer", "provider": "Google", "difficulty": "Intermediate"},
        ],
        "project_recommendations": [
            {
                "title": "Social Media Platform",
                "description": "Build a full social media app with feeds, profiles, real-time notifications, and chat.",
                "skills_demonstrated": ["React", "Node.js", "Database", "WebSockets", "Authentication"],
                "difficulty": "Advanced",
                "estimated_hours": 60,
            },
            {
                "title": "Project Management Tool",
                "description": "Create a Trello-like kanban board with drag-and-drop, team collaboration, and real-time sync.",
                "skills_demonstrated": ["Full Stack", "Real-time", "Drag & Drop", "Team Features"],
                "difficulty": "Intermediate",
                "estimated_hours": 45,
            },
            {
                "title": "E-Commerce Store",
                "description": "Build a complete online store with product catalog, cart, checkout, and payment integration.",
                "skills_demonstrated": ["Full Stack", "Payment Integration", "Database", "Authentication"],
                "difficulty": "Intermediate",
                "estimated_hours": 50,
            },
        ],
        "learning_resources": [
            {"name": "Full Stack Open", "url": "https://fullstackopen.com", "type": "Course", "free": True},
            {"name": "The Odin Project", "url": "https://theodinproject.com", "type": "Course", "free": True},
            {"name": "freeCodeCamp", "url": "https://freecodecamp.org", "type": "Course", "free": True},
            {"name": "Fireship.io", "url": "https://fireship.io", "type": "Videos", "free": True},
        ],
        "difficulty": "Hard",
        "average_preparation_weeks": 16,
    },

    "data_scientist": {
        "metadata": {
            "id": "data_scientist",
            "title": "Data Scientist",
            "description": "Extract insights from data using statistics, machine learning, and visualization.",
            "industry": "Technology / Analytics",
            "experience_level": "Entry to Mid-Level",
            "avg_salary_range": "$80,000 - $160,000",
        },
        "must_have_skills": [
            "Python (Pandas, NumPy, Scikit-learn)",
            "Statistics & Probability",
            "Machine Learning Algorithms",
            "Data Visualization (Matplotlib, Seaborn)",
            "SQL & Database Queries",
            "Exploratory Data Analysis (EDA)",
            "Feature Engineering",
            "Jupyter Notebooks",
            "Linear Algebra & Calculus",
            "Data Cleaning & Preprocessing",
        ],
        "good_to_have_skills": [
            "Deep Learning (TensorFlow/PyTorch)",
            "Natural Language Processing",
            "Big Data Tools (Spark, Hadoop)",
            "Cloud ML Services (SageMaker, Vertex AI)",
            "A/B Testing",
            "Time Series Analysis",
            "Computer Vision",
            "MLOps & Model Deployment",
            "R Programming",
            "Data Engineering Basics",
        ],
        "soft_skills": [
            "Analytical Thinking",
            "Storytelling with Data",
            "Business Acumen",
            "Curiosity",
            "Communication",
            "Critical Thinking",
        ],
        "ats_keywords": [
            "data science", "machine learning", "statistical analysis",
            "Python", "pandas", "scikit-learn", "deep learning",
            "data visualization", "predictive modeling", "EDA",
            "feature engineering", "A/B testing", "NLP",
            "neural networks", "regression", "classification",
            "clustering", "data pipeline", "SQL", "TensorFlow",
        ],
        "interview_topics": [
            "Statistics & Probability (Hypothesis Testing, Distributions)",
            "Machine Learning Algorithms (Regression, Trees, SVM, Ensemble)",
            "Deep Learning Fundamentals",
            "Feature Engineering & Selection",
            "Model Evaluation Metrics (Precision, Recall, F1, AUC)",
            "SQL Queries & Data Manipulation",
            "A/B Testing & Experiment Design",
            "Data Visualization & Communication",
            "Python Coding & Data Manipulation",
            "Case Studies & Business Problem Solving",
        ],
        "certifications": [
            {"name": "Google Data Analytics Professional Certificate", "provider": "Google/Coursera", "difficulty": "Beginner"},
            {"name": "IBM Data Science Professional Certificate", "provider": "IBM/Coursera", "difficulty": "Beginner"},
            {"name": "TensorFlow Developer Certificate", "provider": "Google", "difficulty": "Intermediate"},
            {"name": "AWS Certified Machine Learning – Specialty", "provider": "Amazon", "difficulty": "Advanced"},
        ],
        "project_recommendations": [
            {
                "title": "Customer Churn Prediction",
                "description": "Build an ML pipeline to predict customer churn with feature engineering and model comparison.",
                "skills_demonstrated": ["ML Pipeline", "Feature Engineering", "Classification", "Visualization"],
                "difficulty": "Intermediate",
                "estimated_hours": 25,
            },
            {
                "title": "Sentiment Analysis Dashboard",
                "description": "Create an NLP system for analyzing sentiment from social media data with a live dashboard.",
                "skills_demonstrated": ["NLP", "Data Visualization", "API Integration", "Dashboard"],
                "difficulty": "Intermediate",
                "estimated_hours": 35,
            },
            {
                "title": "Recommendation System",
                "description": "Build a movie/product recommendation engine using collaborative and content-based filtering.",
                "skills_demonstrated": ["Recommendation Algorithms", "Matrix Factorization", "Evaluation"],
                "difficulty": "Advanced",
                "estimated_hours": 40,
            },
        ],
        "learning_resources": [
            {"name": "Kaggle Learn", "url": "https://kaggle.com/learn", "type": "Interactive", "free": True},
            {"name": "Andrew Ng's ML Course", "url": "https://coursera.org/learn/machine-learning", "type": "Course", "free": True},
            {"name": "StatQuest YouTube", "url": "https://youtube.com/statquest", "type": "Video", "free": True},
            {"name": "Hands-On ML with Scikit-Learn", "url": "https://oreilly.com", "type": "Book", "free": False},
        ],
        "difficulty": "Hard",
        "average_preparation_weeks": 16,
    },

    "ml_engineer": {
        "metadata": {
            "id": "ml_engineer",
            "title": "Machine Learning Engineer",
            "description": "Build, deploy, and maintain production ML systems and pipelines.",
            "industry": "Technology / AI",
            "experience_level": "Mid-Level",
            "avg_salary_range": "$100,000 - $180,000",
        },
        "must_have_skills": [
            "Python (Advanced)",
            "Machine Learning Algorithms",
            "Deep Learning (TensorFlow/PyTorch)",
            "Data Structures & Algorithms",
            "Model Training & Optimization",
            "MLOps & Model Deployment",
            "Docker & Containerization",
            "Cloud ML Services",
            "Feature Engineering",
            "Version Control (Git, DVC)",
        ],
        "good_to_have_skills": [
            "Kubernetes",
            "Apache Spark / Distributed Computing",
            "LLMs & Generative AI",
            "Model Monitoring & Drift Detection",
            "A/B Testing for Models",
            "ONNX / Model Optimization",
            "Experiment Tracking (MLflow, W&B)",
            "Data Engineering (Airflow, dbt)",
            "Reinforcement Learning",
            "Edge Deployment (TFLite, ONNX Runtime)",
        ],
        "soft_skills": [
            "Research Mindset",
            "System Thinking",
            "Communication",
            "Experimentation",
            "Collaboration",
            "Continuous Learning",
        ],
        "ats_keywords": [
            "machine learning", "deep learning", "MLOps", "model deployment",
            "TensorFlow", "PyTorch", "production ML", "training pipeline",
            "inference", "model optimization", "feature store",
            "experiment tracking", "Docker", "Kubernetes", "cloud",
            "distributed training", "LLM", "generative AI", "NLP",
            "computer vision", "data pipeline",
        ],
        "interview_topics": [
            "ML System Design (End-to-end Pipeline)",
            "Deep Learning Architectures (CNN, RNN, Transformers)",
            "Model Optimization & Quantization",
            "MLOps Best Practices",
            "Distributed Training",
            "Feature Store Design",
            "Model Monitoring & Retraining",
            "Data Structures & Algorithms",
            "System Design for ML",
            "Research Paper Discussion",
        ],
        "certifications": [
            {"name": "TensorFlow Developer Certificate", "provider": "Google", "difficulty": "Intermediate"},
            {"name": "AWS ML Specialty", "provider": "Amazon", "difficulty": "Advanced"},
            {"name": "Google Professional ML Engineer", "provider": "Google", "difficulty": "Advanced"},
        ],
        "project_recommendations": [
            {
                "title": "End-to-End ML Pipeline",
                "description": "Build a complete ML pipeline with data ingestion, training, evaluation, and deployment.",
                "skills_demonstrated": ["MLOps", "Pipeline", "Deployment", "Monitoring"],
                "difficulty": "Advanced",
                "estimated_hours": 50,
            },
            {
                "title": "Real-Time Object Detection API",
                "description": "Deploy a computer vision model as a REST API with Docker and GPU inference.",
                "skills_demonstrated": ["Computer Vision", "API", "Docker", "Model Serving"],
                "difficulty": "Advanced",
                "estimated_hours": 40,
            },
            {
                "title": "LLM Fine-Tuning & Deployment",
                "description": "Fine-tune a language model for a specific domain and deploy with streaming inference.",
                "skills_demonstrated": ["LLM", "Fine-tuning", "Inference", "API"],
                "difficulty": "Advanced",
                "estimated_hours": 45,
            },
        ],
        "learning_resources": [
            {"name": "Fast.ai", "url": "https://fast.ai", "type": "Course", "free": True},
            {"name": "MLOps Community", "url": "https://mlops.community", "type": "Community", "free": True},
            {"name": "Made With ML", "url": "https://madewithml.com", "type": "Course", "free": True},
            {"name": "Hugging Face Course", "url": "https://huggingface.co/learn", "type": "Course", "free": True},
        ],
        "difficulty": "Hard",
        "average_preparation_weeks": 20,
    },

    "devops_engineer": {
        "metadata": {
            "id": "devops_engineer",
            "title": "DevOps Engineer",
            "description": "Automate infrastructure, manage CI/CD pipelines, and ensure system reliability.",
            "industry": "Technology",
            "experience_level": "Mid-Level",
            "avg_salary_range": "$90,000 - $160,000",
        },
        "must_have_skills": [
            "Linux System Administration",
            "Docker & Containerization",
            "CI/CD Pipelines (Jenkins/GitHub Actions)",
            "Cloud Platforms (AWS/GCP/Azure)",
            "Infrastructure as Code (Terraform)",
            "Shell Scripting (Bash)",
            "Kubernetes",
            "Networking Fundamentals",
            "Monitoring & Logging (Prometheus/Grafana)",
            "Git & Version Control",
        ],
        "good_to_have_skills": [
            "Ansible/Chef/Puppet",
            "Service Mesh (Istio)",
            "Security & Compliance",
            "Serverless Architecture",
            "Database Administration",
            "Load Balancing & CDN",
            "Chaos Engineering",
            "Python/Go Scripting",
            "ArgoCD / GitOps",
            "Observability (OpenTelemetry)",
        ],
        "soft_skills": [
            "Automation Mindset",
            "Problem Solving",
            "Communication",
            "On-call Readiness",
            "Documentation Skills",
            "Continuous Improvement",
        ],
        "ats_keywords": [
            "DevOps", "CI/CD", "Docker", "Kubernetes", "infrastructure as code",
            "Terraform", "cloud", "AWS", "GCP", "Azure", "automation",
            "monitoring", "logging", "deployment", "Linux", "containerization",
            "pipeline", "shell scripting", "microservices", "SRE",
            "reliability", "scalability",
        ],
        "interview_topics": [
            "CI/CD Pipeline Design",
            "Container Orchestration (Kubernetes)",
            "Infrastructure as Code (Terraform, CloudFormation)",
            "Cloud Architecture & Services",
            "Monitoring, Alerting & Incident Response",
            "Networking (DNS, Load Balancers, VPN)",
            "Security & Compliance",
            "Linux System Administration",
            "Scripting & Automation",
            "Disaster Recovery & Backup Strategies",
        ],
        "certifications": [
            {"name": "AWS Solutions Architect – Associate", "provider": "Amazon", "difficulty": "Intermediate"},
            {"name": "Certified Kubernetes Administrator", "provider": "CNCF", "difficulty": "Advanced"},
            {"name": "HashiCorp Terraform Associate", "provider": "HashiCorp", "difficulty": "Intermediate"},
            {"name": "Google Professional Cloud DevOps Engineer", "provider": "Google", "difficulty": "Advanced"},
        ],
        "project_recommendations": [
            {
                "title": "Automated Deployment Pipeline",
                "description": "Build a full CI/CD pipeline with testing, staging, and production deployments.",
                "skills_demonstrated": ["CI/CD", "Docker", "Testing", "Automation"],
                "difficulty": "Intermediate",
                "estimated_hours": 30,
            },
            {
                "title": "Kubernetes Cluster Setup",
                "description": "Deploy a multi-service application on Kubernetes with monitoring and auto-scaling.",
                "skills_demonstrated": ["Kubernetes", "Monitoring", "Networking", "Scaling"],
                "difficulty": "Advanced",
                "estimated_hours": 40,
            },
            {
                "title": "Infrastructure as Code with Terraform",
                "description": "Provision cloud infrastructure using Terraform modules with state management.",
                "skills_demonstrated": ["Terraform", "Cloud", "IaC", "Modules"],
                "difficulty": "Intermediate",
                "estimated_hours": 25,
            },
        ],
        "learning_resources": [
            {"name": "KodeKloud", "url": "https://kodekloud.com", "type": "Course", "free": False},
            {"name": "Linux Academy", "url": "https://acloudguru.com", "type": "Course", "free": False},
            {"name": "DevOps Roadmap", "url": "https://roadmap.sh/devops", "type": "Roadmap", "free": True},
            {"name": "Kubernetes Official Docs", "url": "https://kubernetes.io/docs", "type": "Documentation", "free": True},
        ],
        "difficulty": "Hard",
        "average_preparation_weeks": 14,
    },

    "cloud_architect": {
        "metadata": {
            "id": "cloud_architect",
            "title": "Cloud Architect",
            "description": "Design and manage scalable, secure cloud infrastructure and solutions.",
            "industry": "Technology",
            "experience_level": "Senior",
            "avg_salary_range": "$120,000 - $200,000",
        },
        "must_have_skills": [
            "AWS / GCP / Azure (Deep Expertise)",
            "Cloud Architecture Design",
            "Networking (VPC, Subnets, Load Balancers)",
            "Security & IAM",
            "Infrastructure as Code",
            "Serverless Computing",
            "Microservices Architecture",
            "Cost Optimization",
            "High Availability & Disaster Recovery",
            "Containerization & Orchestration",
        ],
        "good_to_have_skills": [
            "Multi-Cloud Strategies",
            "Data Architecture (Data Lakes, Warehouses)",
            "Edge Computing",
            "Compliance & Governance",
            "Migration Strategies",
            "AI/ML Cloud Services",
            "Event-Driven Architecture",
            "API Gateway Management",
            "Cloud-Native Application Design",
            "FinOps",
        ],
        "soft_skills": [
            "Strategic Thinking",
            "Stakeholder Communication",
            "Decision Making",
            "Leadership",
            "Business Understanding",
            "Mentoring",
        ],
        "ats_keywords": [
            "cloud architecture", "AWS", "GCP", "Azure", "infrastructure design",
            "scalability", "high availability", "disaster recovery",
            "security", "IAM", "networking", "serverless", "microservices",
            "cost optimization", "migration", "containerization",
            "Kubernetes", "Terraform", "cloud-native", "multi-cloud",
        ],
        "interview_topics": [
            "Cloud Architecture Design & Patterns",
            "Multi-Region & Multi-AZ Deployments",
            "Security Architecture & Zero Trust",
            "Cost Optimization Strategies",
            "Migration Planning (Lift & Shift, Refactor)",
            "Networking Architecture (VPC, CDN, DNS)",
            "Data Architecture (Lakes, Warehouses, Pipelines)",
            "Serverless & Event-Driven Design",
            "Compliance & Governance",
            "Disaster Recovery & Business Continuity",
        ],
        "certifications": [
            {"name": "AWS Solutions Architect – Professional", "provider": "Amazon", "difficulty": "Advanced"},
            {"name": "Google Professional Cloud Architect", "provider": "Google", "difficulty": "Advanced"},
            {"name": "Azure Solutions Architect Expert", "provider": "Microsoft", "difficulty": "Advanced"},
        ],
        "project_recommendations": [
            {
                "title": "Multi-Region Cloud Architecture",
                "description": "Design and implement a fault-tolerant multi-region application with automated failover.",
                "skills_demonstrated": ["Cloud Design", "High Availability", "Networking", "Automation"],
                "difficulty": "Advanced",
                "estimated_hours": 50,
            },
            {
                "title": "Serverless Data Pipeline",
                "description": "Build a serverless ETL pipeline with event triggers, transformation, and storage.",
                "skills_demonstrated": ["Serverless", "Data Pipeline", "Event-Driven", "Storage"],
                "difficulty": "Intermediate",
                "estimated_hours": 35,
            },
        ],
        "learning_resources": [
            {"name": "AWS Well-Architected Framework", "url": "https://aws.amazon.com/architecture/well-architected", "type": "Documentation", "free": True},
            {"name": "Google Cloud Architecture Center", "url": "https://cloud.google.com/architecture", "type": "Documentation", "free": True},
            {"name": "A Cloud Guru", "url": "https://acloudguru.com", "type": "Course", "free": False},
        ],
        "difficulty": "Very Hard",
        "average_preparation_weeks": 20,
    },

    "cybersecurity_analyst": {
        "metadata": {
            "id": "cybersecurity_analyst",
            "title": "Cybersecurity Analyst",
            "description": "Protect organizations from cyber threats through monitoring, analysis, and incident response.",
            "industry": "Technology / Security",
            "experience_level": "Entry to Mid-Level",
            "avg_salary_range": "$65,000 - $130,000",
        },
        "must_have_skills": [
            "Network Security",
            "Security Information & Event Management (SIEM)",
            "Vulnerability Assessment",
            "Incident Response",
            "Firewalls & IDS/IPS",
            "Linux & Windows Security",
            "TCP/IP & Networking Protocols",
            "Malware Analysis Basics",
            "Risk Assessment",
            "Security Frameworks (NIST, ISO 27001)",
        ],
        "good_to_have_skills": [
            "Penetration Testing",
            "Cloud Security",
            "Python Scripting for Security",
            "Digital Forensics",
            "Threat Intelligence",
            "Zero Trust Architecture",
            "Compliance (GDPR, HIPAA, PCI-DSS)",
            "SOAR Platforms",
            "Cryptography",
            "Reverse Engineering",
        ],
        "soft_skills": [
            "Analytical Thinking",
            "Attention to Detail",
            "Continuous Learning",
            "Communication",
            "Ethical Judgment",
            "Stress Management",
        ],
        "ats_keywords": [
            "cybersecurity", "information security", "network security",
            "incident response", "vulnerability assessment", "SIEM",
            "firewall", "IDS", "IPS", "threat detection",
            "risk assessment", "security monitoring", "malware analysis",
            "penetration testing", "compliance", "NIST", "ISO 27001",
            "encryption", "zero trust", "SOC",
        ],
        "interview_topics": [
            "Network Security Fundamentals",
            "Common Attack Vectors & Mitigations",
            "Incident Response Procedures",
            "SIEM Tools & Log Analysis",
            "Vulnerability Scanning & Assessment",
            "Cryptography Basics",
            "Security Frameworks & Compliance",
            "Web Application Security (OWASP Top 10)",
            "Operating System Security",
            "Threat Modeling",
        ],
        "certifications": [
            {"name": "CompTIA Security+", "provider": "CompTIA", "difficulty": "Beginner"},
            {"name": "Certified Ethical Hacker (CEH)", "provider": "EC-Council", "difficulty": "Intermediate"},
            {"name": "CompTIA CySA+", "provider": "CompTIA", "difficulty": "Intermediate"},
            {"name": "CISSP", "provider": "ISC2", "difficulty": "Advanced"},
        ],
        "project_recommendations": [
            {
                "title": "Home Lab Security Setup",
                "description": "Build a virtual security lab with firewall, IDS, SIEM, and vulnerable VMs for practice.",
                "skills_demonstrated": ["Network Security", "SIEM", "IDS", "Virtual Labs"],
                "difficulty": "Intermediate",
                "estimated_hours": 30,
            },
            {
                "title": "Security Audit Report",
                "description": "Conduct a security assessment of a web application and produce a professional report.",
                "skills_demonstrated": ["Vulnerability Assessment", "Reporting", "OWASP", "Risk Analysis"],
                "difficulty": "Intermediate",
                "estimated_hours": 25,
            },
        ],
        "learning_resources": [
            {"name": "TryHackMe", "url": "https://tryhackme.com", "type": "Interactive", "free": True},
            {"name": "Hack The Box", "url": "https://hackthebox.com", "type": "Practice", "free": True},
            {"name": "SANS Cyber Aces", "url": "https://cyberaces.org", "type": "Course", "free": True},
            {"name": "OverTheWire Wargames", "url": "https://overthewire.org", "type": "Practice", "free": True},
        ],
        "difficulty": "Medium",
        "average_preparation_weeks": 14,
    },

    "mobile_developer": {
        "metadata": {
            "id": "mobile_developer",
            "title": "Mobile App Developer",
            "description": "Design and build mobile applications for iOS and Android platforms.",
            "industry": "Technology",
            "experience_level": "Entry to Mid-Level",
            "avg_salary_range": "$70,000 - $150,000",
        },
        "must_have_skills": [
            "React Native or Flutter",
            "JavaScript/TypeScript or Dart",
            "Mobile UI/UX Design Principles",
            "REST API Integration",
            "State Management",
            "Git & Version Control",
            "App Store Deployment",
            "Mobile Testing & Debugging",
            "Local Storage & SQLite",
            "Push Notifications",
        ],
        "good_to_have_skills": [
            "Native iOS (Swift) or Android (Kotlin)",
            "Firebase",
            "GraphQL",
            "CI/CD for Mobile",
            "App Performance Optimization",
            "Animations & Gestures",
            "Offline-First Architecture",
            "In-App Purchases",
            "Analytics Integration",
            "Accessibility (Mobile)",
        ],
        "soft_skills": [
            "User-Centric Thinking",
            "Attention to Detail",
            "Creativity",
            "Platform Awareness",
            "Problem Solving",
            "Communication",
        ],
        "ats_keywords": [
            "mobile development", "React Native", "Flutter", "iOS", "Android",
            "cross-platform", "mobile UI", "app development",
            "REST API", "push notifications", "app store",
            "Firebase", "SQLite", "state management",
            "responsive", "native", "mobile testing",
        ],
        "interview_topics": [
            "Mobile Architecture Patterns (MVC, MVVM, Clean)",
            "React Native / Flutter Deep Dive",
            "State Management in Mobile Apps",
            "API Integration & Offline Sync",
            "Performance Optimization",
            "Navigation Patterns",
            "Mobile Security Best Practices",
            "Testing Strategies (Unit, Widget, Integration)",
            "App Store Guidelines & Submission",
            "Push Notifications Architecture",
        ],
        "certifications": [
            {"name": "Google Associate Android Developer", "provider": "Google", "difficulty": "Intermediate"},
            {"name": "Meta React Native Specialization", "provider": "Meta/Coursera", "difficulty": "Intermediate"},
        ],
        "project_recommendations": [
            {
                "title": "Fitness Tracker App",
                "description": "Build a mobile app with step tracking, workout logging, progress charts, and notifications.",
                "skills_demonstrated": ["Mobile UI", "Local Storage", "Charts", "Notifications"],
                "difficulty": "Intermediate",
                "estimated_hours": 35,
            },
            {
                "title": "Recipe Sharing App",
                "description": "Create a social recipe app with image uploads, search, favorites, and offline access.",
                "skills_demonstrated": ["API", "Image Upload", "Offline", "Social Features"],
                "difficulty": "Intermediate",
                "estimated_hours": 40,
            },
        ],
        "learning_resources": [
            {"name": "React Native Docs", "url": "https://reactnative.dev", "type": "Documentation", "free": True},
            {"name": "Flutter Docs", "url": "https://flutter.dev", "type": "Documentation", "free": True},
            {"name": "Academind", "url": "https://academind.com", "type": "Course", "free": False},
        ],
        "difficulty": "Medium",
        "average_preparation_weeks": 12,
    },

    "product_manager": {
        "metadata": {
            "id": "product_manager",
            "title": "Product Manager",
            "description": "Define product vision, strategy, and roadmap while bridging business and engineering teams.",
            "industry": "Technology",
            "experience_level": "Mid-Level",
            "avg_salary_range": "$90,000 - $170,000",
        },
        "must_have_skills": [
            "Product Strategy & Vision",
            "User Research & Interviews",
            "Data Analysis & Metrics",
            "Agile & Scrum Methodology",
            "Roadmap Planning",
            "Stakeholder Management",
            "Wireframing & Prototyping",
            "A/B Testing",
            "Market Analysis",
            "Technical Communication",
        ],
        "good_to_have_skills": [
            "SQL & Data Querying",
            "Growth Hacking",
            "UX Design Principles",
            "Financial Modeling",
            "API Understanding",
            "Competitive Analysis Frameworks",
            "OKR Setting",
            "Customer Journey Mapping",
            "Analytics Tools (Amplitude, Mixpanel)",
            "Basic Coding Knowledge",
        ],
        "soft_skills": [
            "Leadership",
            "Communication",
            "Empathy",
            "Strategic Thinking",
            "Negotiation",
            "Decision Making",
            "Influence Without Authority",
        ],
        "ats_keywords": [
            "product management", "product strategy", "roadmap",
            "agile", "scrum", "user research", "data-driven",
            "stakeholder management", "A/B testing", "KPIs",
            "OKR", "user stories", "sprint planning", "backlog",
            "market analysis", "competitive analysis", "PRD",
            "product requirements", "go-to-market", "metrics",
        ],
        "interview_topics": [
            "Product Sense (Design a Product)",
            "Strategy Questions",
            "Metrics & Analytics",
            "Technical Communication",
            "Behavioral Questions (Leadership, Conflict)",
            "Estimation & Market Sizing",
            "Prioritization Frameworks (RICE, MoSCoW)",
            "User Research Methods",
            "Roadmap Presentation",
            "Case Studies",
        ],
        "certifications": [
            {"name": "Google Project Management Certificate", "provider": "Google/Coursera", "difficulty": "Beginner"},
            {"name": "Certified Scrum Product Owner", "provider": "Scrum Alliance", "difficulty": "Intermediate"},
            {"name": "Pragmatic Institute Certification", "provider": "Pragmatic Institute", "difficulty": "Intermediate"},
        ],
        "project_recommendations": [
            {
                "title": "Product Case Study Portfolio",
                "description": "Write detailed case studies analyzing 3 products — including problems, solutions, and metrics.",
                "skills_demonstrated": ["Product Analysis", "Metrics", "Writing", "Strategy"],
                "difficulty": "Beginner",
                "estimated_hours": 20,
            },
            {
                "title": "MVP Launch Simulation",
                "description": "Define, spec, and simulate launching an MVP with a PRD, wireframes, and go-to-market plan.",
                "skills_demonstrated": ["PRD", "Wireframing", "Strategy", "Go-to-Market"],
                "difficulty": "Intermediate",
                "estimated_hours": 30,
            },
        ],
        "learning_resources": [
            {"name": "Lenny's Newsletter", "url": "https://lennysnewsletter.com", "type": "Newsletter", "free": True},
            {"name": "Product School", "url": "https://productschool.com", "type": "Course", "free": False},
            {"name": "Inspired (Marty Cagan)", "url": "https://svpg.com/inspired", "type": "Book", "free": False},
            {"name": "Reforge", "url": "https://reforge.com", "type": "Course", "free": False},
        ],
        "difficulty": "Medium",
        "average_preparation_weeks": 10,
    },

    "ux_designer": {
        "metadata": {
            "id": "ux_designer",
            "title": "UX Designer",
            "description": "Research, design, and test user experiences for digital products.",
            "industry": "Technology / Design",
            "experience_level": "Entry to Mid-Level",
            "avg_salary_range": "$65,000 - $140,000",
        },
        "must_have_skills": [
            "User Research & Testing",
            "Wireframing & Prototyping",
            "Figma",
            "Information Architecture",
            "Interaction Design",
            "Visual Design Principles",
            "Design Systems",
            "Usability Testing",
            "User Journey Mapping",
            "Responsive Design",
        ],
        "good_to_have_skills": [
            "HTML/CSS Basics",
            "Motion Design",
            "Accessibility Design (WCAG)",
            "Design Thinking Facilitation",
            "Data-Informed Design",
            "Content Strategy",
            "Brand Design",
            "Illustration",
            "Design Ops",
            "AR/VR Design",
        ],
        "soft_skills": [
            "Empathy",
            "Communication",
            "Collaboration",
            "Creativity",
            "Storytelling",
            "Critical Thinking",
            "Presentation Skills",
        ],
        "ats_keywords": [
            "UX design", "user experience", "user research", "wireframing",
            "prototyping", "Figma", "usability testing", "interaction design",
            "information architecture", "design systems", "user-centered",
            "accessibility", "responsive design", "visual design",
            "user journey", "personas", "A/B testing", "design thinking",
        ],
        "interview_topics": [
            "Design Process & Methodology",
            "Portfolio Walkthrough & Case Studies",
            "User Research Methods",
            "Wireframing & Prototyping Exercise",
            "Design Critique",
            "Accessibility Standards",
            "Design System Architecture",
            "Stakeholder Communication",
            "Usability Testing Design",
            "Design Challenge (Whiteboard)",
        ],
        "certifications": [
            {"name": "Google UX Design Professional Certificate", "provider": "Google/Coursera", "difficulty": "Beginner"},
            {"name": "Nielsen Norman UX Certification", "provider": "NNGroup", "difficulty": "Intermediate"},
            {"name": "Interaction Design Foundation", "provider": "IxDF", "difficulty": "Beginner"},
        ],
        "project_recommendations": [
            {
                "title": "UX Case Study: App Redesign",
                "description": "Conduct user research, create personas, wireframes, and a high-fidelity prototype for an app redesign.",
                "skills_demonstrated": ["Research", "Wireframing", "Prototyping", "Testing"],
                "difficulty": "Intermediate",
                "estimated_hours": 30,
            },
            {
                "title": "Design System Creation",
                "description": "Build a comprehensive design system with components, tokens, and documentation in Figma.",
                "skills_demonstrated": ["Design Systems", "Figma", "Documentation", "Components"],
                "difficulty": "Advanced",
                "estimated_hours": 40,
            },
        ],
        "learning_resources": [
            {"name": "Google UX Design (Coursera)", "url": "https://coursera.org/google-ux-design", "type": "Course", "free": True},
            {"name": "Nielsen Norman Group Articles", "url": "https://nngroup.com", "type": "Articles", "free": True},
            {"name": "Laws of UX", "url": "https://lawsofux.com", "type": "Reference", "free": True},
            {"name": "Figma Community", "url": "https://figma.com/community", "type": "Resources", "free": True},
        ],
        "difficulty": "Medium",
        "average_preparation_weeks": 10,
    },
}


def get_all_role_ids() -> list[str]:
    """Return a list of all available role IDs."""
    return list(CAREER_ROLES.keys())


def get_role_data(role_id: str) -> dict | None:
    """Return the full data for a specific role, or None if not found."""
    return CAREER_ROLES.get(role_id)
